### ISSUE TITLE
yarn run link? 'link' script does not exist?

### ISSUE THREAD

**Issue by litt1e-p** [trazyn/JJJkkk#2]
I can not find `link` script in package.json when using `yarn run link to link react native dependencies`, can you do some help? thanks

**Comment by trazyn** [comment]
Sorry it's `react-native link`, already update `README`

**Comment by litt1e-p** [comment]
there are some errors raised as below:
```
error: bundling failed: Error: Unable to resolve module `../node_modules/react-native/src/utils/MobxProvider` from `/Users/mac/Desktop/JJJkkk/src/index.js`: The module `../node_modules/react-native/src/utils/MobxProvider` could not be found from `/Users/mac/Desktop/JJJkkk/src/index.js`. Indeed, none of these files exist:
* `/Users/mac/Desktop/JJJkkk/node_modules/react-native/src/utils/MobxProvider(.native||.ios.js|.native.js|.js|.ios.json|.native.json|.json)`
  * `/Users/mac/Desktop/JJJkkk/node_modules/react-native/src/utils/MobxProvider/index(.native||.ios.js|.native.js|.js|.ios.json|.native.json|.json)`
    at ModuleResolver.resolveDependency (/Users/mac/Desktop/JJJkkk/node_modules/metro/src/node-haste/DependencyGraph/ModuleResolution.js:311:1122)
    at ResolutionRequest.resolveDependency (/Users/mac/Desktop/JJJkkk/node_modules/metro/src/node-haste/DependencyGraph/ResolutionRequest.js:96:16)
    at DependencyGraph.resolveDependency (/Users/mac/Desktop/JJJkkk/node_modules/metro/src/node-haste/DependencyGraph.js:269:4352)
    at /Users/mac/Desktop/JJJkkk/node_modules/metro/src/DeltaBundler/traverseDependencies.js:201:36
    at Generator.next (<anonymous>)
    at step (/Users/mac/Desktop/JJJkkk/node_modules/metro/src/DeltaBundler/traverseDependencies.js:256:306)
    at /Users/mac/Desktop/JJJkkk/node_modules/metro/src/DeltaBundler/traverseDependencies.js:256:536
    at new Promise (<anonymous>)
    at /Users/mac/Desktop/JJJkkk/node_modules/metro/src/DeltaBundler/traverseDependencies.js:256:217
    at addDependency (/Users/mac/Desktop/JJJkkk/node_modules/metro/src/DeltaBundler/traverseDependencies.js:256:92)
 BUNDLE  [ios, dev] ./index.js ▓░░░░░░░░░░░░░░░ 6.4% (103/407), failed.

```
did I miss some steps to build it correctly?

**Comment by trazyn** [comment]
You need  to reset npm cache or reinstall modules(`rm -rf node_modules/ && npm i`)

**Comment by litt1e-p** [comment]
same error were still raised.

**Comment by trazyn** [comment]
The problem caused by `babel-plugin-module-resolver`, maybe can help for u [Support for React Native](https://github.com/tleunen/babel-plugin-module-resolver/issues/29)

**Comment by litt1e-p** [comment]
thanks for your answer, now the app could run successfully on my iPhone with `react-native start -- --reset-cache` & `cmd+r` in Xcode, but it still could not run in simulator with `yarn run ios`,  the `babel-plugin-module-resolver` maybe exists some bug there. I do not know why
