### ISSUE TITLE
iOS 启动错误

### ISSUE THREAD

**Issue by chencao187** [trazyn/JJJkkk#7]
simulator显示：
<img width="342" alt="screen shot 2018-09-12 at 10 22 49 pm" src="https://user-images.githubusercontent.com/17312180/45424623-69442700-b6da-11e8-9f98-85cd948a1d0f.png">

Metro bundle 显示：

```
Looking for JS files in
   /Users/dchen/JJJkkk 


Metro Bundler ready.

Loading dependency graph, done.
error: bundling failed: Error: Unable to resolve module `../node_modules/react-native/src/utils/MobxProvider` from `/Users/dchen/JJJkkk/src/index.js`: The module `../node_modules/react-native/src/utils/MobxProvider` could not be found from `/Users/dchen/JJJkkk/src/index.js`. Indeed, none of these files exist:

  * `/Users/dchen/JJJkkk/node_modules/react-native/src/utils/MobxProvider(.native||.ios.js|.native.js|.js|.ios.json|.native.json|.json)`
  * `/Users/dchen/JJJkkk/node_modules/react-native/src/utils/MobxProvider/index(.native||.ios.js|.native.js|.js|.ios.json|.native.json|.json)`
    at ModuleResolver.resolveDependency (/Users/dchen/JJJkkk/node_modules/metro/src/node-haste/DependencyGraph/ModuleResolution.js:161:851)
    at ResolutionRequest.resolveDependency (/Users/dchen/JJJkkk/node_modules/metro/src/node-haste/DependencyGraph/ResolutionRequest.js:91:16)
    at DependencyGraph.resolveDependency (/Users/dchen/JJJkkk/node_modules/metro/src/node-haste/DependencyGraph.js:272:4579)
    at dependencies.map.relativePath (/Users/dchen/JJJkkk/node_modules/metro/src/DeltaBundler/traverseDependencies.js:376:19)
    at Array.map (<anonymous>)
    at resolveDependencies (/Users/dchen/JJJkkk/node_modules/metro/src/DeltaBundler/traverseDependencies.js:374:16)
    at /Users/dchen/JJJkkk/node_modules/metro/src/DeltaBundler/traverseDependencies.js:212:33
    at Generator.next (<anonymous>)
    at step (/Users/dchen/JJJkkk/node_modules/metro/src/DeltaBundler/traverseDependencies.js:297:313)
    at /Users/dchen/JJJkkk/node_modules/metro/src/DeltaBundler/traverseDependencies.js:297:473
 BUNDLE  [ios, dev] ./index.js ░░░░░░░░░░░░░░░░ 0.0% (0/1), failed.

error: bundling failed: Error: Unable to resolve module `../node_modules/react-native/src/utils/MobxProvider` from `/Users/dchen/JJJkkk/src/index.js`: The module `../node_modules/react-native/src/utils/MobxProvider` could not be found from `/Users/dchen/JJJkkk/src/index.js`. Indeed, none of these files exist:

  * `/Users/dchen/JJJkkk/node_modules/react-native/src/utils/MobxProvider(.native||.ios.js|.native.js|.js|.ios.json|.native.json|.json)`
  * `/Users/dchen/JJJkkk/node_modules/react-native/src/utils/MobxProvider/index(.native||.ios.js|.native.js|.js|.ios.json|.native.json|.json)`
    at ModuleResolver.resolveDependency (/Users/dchen/JJJkkk/node_modules/metro/src/node-haste/DependencyGraph/ModuleResolution.js:161:851)
    at ResolutionRequest.resolveDependency (/Users/dchen/JJJkkk/node_modules/metro/src/node-haste/DependencyGraph/ResolutionRequest.js:91:16)
    at DependencyGraph.resolveDependency (/Users/dchen/JJJkkk/node_modules/metro/src/node-haste/DependencyGraph.js:272:4579)
    at dependencies.map.relativePath (/Users/dchen/JJJkkk/node_modules/metro/src/DeltaBundler/traverseDependencies.js:376:19)
    at Array.map (<anonymous>)
    at resolveDependencies (/Users/dchen/JJJkkk/node_modules/metro/src/DeltaBundler/traverseDependencies.js:374:16)
    at /Users/dchen/JJJkkk/node_modules/metro/src/DeltaBundler/traverseDependencies.js:212:33
    at Generator.next (<anonymous>)
    at step (/Users/dchen/JJJkkk/node_modules/metro/src/DeltaBundler/traverseDependencies.js:297:313)
    at /Users/dchen/JJJkkk/node_modules/metro/src/DeltaBundler/traverseDependencies.js:297:473
 BUNDLE  [ios, dev] ./index.js ░░░░░░░░░░░░░░░░ 0.0% (0/1), failed.
```

MacOS 10.14 beta
Xcode 9.4.1
react-native-cli: 2.0.1
react-native: 0.55.4

**Comment by trazyn** [comment]
emmmm
```
npm start -- --reset-cache
```
参考 #5
